server:
  port: 8090


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/uaa/oauth/token
      client:
        registration:
          gateway-service:
            provider: uaa
            client-id: gateway-service
            client-secret: gateway-service-secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,resource.read
          #model-manage:
            #provider: uaa
            #client-id: model-manage
            #client-secret: model-manage-secret
            #authorization-grant-type: authorization_code
            #redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            #scope: openid,profile,email,resource.read
        provider:
          uaa:
            authorization-uri: http://localhost:9090/uaa/oauth/authorize
            token-uri: http://localhost:9090/uaa/oauth/token
            user-info-uri: http://localhost:9090/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9090/uaa/token_keys
          #resourceserver:
          #jwt:
          #jwk-set-uri: http://localhost:9090/uaa/token_keys


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO