server:
  port: 8089

spring:
  application:
    name: client-two

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.hostname}:8761/eureka
